rp:
  image: enalean/tuleap-reverseproxy
  links:
   - web:tuleap-web
  volumes_from:
   - tuleap_reverseproxy_data

web:
  container_name: tuleap-web
  image: enalean/tuleap-aio-dev:nodb
  links:
   - ldap:ldap
   - db:db
  volumes:
   - .:/usr/share/tuleap
   - ../tuleap-plugins:/usr/share/tuleap-plugins
  env_file:
   - .env
  volumes_from:
   - tuleap_data

ldap:
  image: enalean/ldap
  env_file:
   - .env
  volumes_from:
   - tuleap_ldap_data

es:
  image: enalean/elasticsearch-tuleap
  volumes_from:
   - tuleap_es_data
  command: -Des.script.disable_dynamic=false

gerrit:
  container_name: tuleap-gerrit
  image: enalean/gerrit-tuleap:2.12
  volumes_from:
   - tuleap_gerrit_data
  env_file:
   - .env
  links:
   - ldap:ldap
   - web:tuleap

db:
  image: mysql:5.5
  env_file:
   - .env
  volumes_from:
   - tuleap_db_data

graphite:
  container_name: tuleap-graphite
  image: hopsoft/graphite-statsd
  volumes:
   - tuleap-graphite-graphite-storage:/opt/graphite/storage
