version: "2"

services:
  reverse-proxy:
    image: enalean/tuleap-reverseproxy:distlp-1.1
    command: /tuleap/tools/distlp/reverse-proxy/run.sh
    volumes_from:
          - container:tuleap_data # Needed for configuration (platform name)
    volumes:
      - .:/tuleap
    depends_on:
      - backend-web
      - backend-svn

  backend-web:
    image: enalean/tuleap-aio-dev:c6-php56-nginx18-v1.5
    environment:
      RUN_COMMAND: "php /usr/share/tuleap/tools/distlp/backend-web/run.php"
    volumes:
      - .:/usr/share/tuleap
      - ../tuleap-plugins:/usr/share/tuleap-plugins
    env_file:
      - .env
    volumes_from:
      - container:tuleap_data
    depends_on:
      - ldap
      - db
      - rabbitmq

  backend-svn:
    image: enalean/tuleap-dev:1.4
    command: /usr/share/tuleap/tools/distlp/backend-svn/backend-svn.sh
    volumes_from:
      - container:tuleap_data
    volumes:
      - .:/usr/share/tuleap
    depends_on:
      - ldap
      - db
      - rabbitmq

  ldap:
    image: enalean/ldap
    env_file:
      - .env
    volumes_from:
      - container:tuleap_ldap_data

  db:
    image: mysql:5.5
    env_file:
      - .env
    volumes_from:
      - container:tuleap_db_data

  rabbitmq:
    image: rabbitmq:3.6
    env_file:
      - .env
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  rabbitmq-data:
