version: "2"

services:
  web:
    container_name: tuleap-web
    image: enalean/tuleap-aio-dev:c6-php56-nginx
    volumes:
    - .:/usr/share/tuleap
    - ../tuleap-plugins:/usr/share/tuleap-plugins
    - tuleap-data:/data
    env_file:
    - .env
    depends_on:
    - ldap
    - db

  ldap:
    image: enalean/ldap
    env_file:
    - .env
    volumes:
    - ldap-data:/data

  gerrit:
    container_name: tuleap-gerrit
    image: enalean/gerrit-tuleap:2.12
    volumes:
    - gerrit-data:/home/gerrit
    env_file:
    - .env
    depends_on:
    - ldap
    - db

  db:
    image: mysql:5.5
    env_file:
    - .env
    volumes:
    - db-data:/var/lib/mysql

  graphite:
    container_name: tuleap-graphite
    image: hopsoft/graphite-statsd
    volumes:
    - graphite-data:/opt/graphite/storage

  rabbitmq:
    image: rabbitmq:3.6
    env_file:
      - .env
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  tuleap-data:
  ldap-data:
  gerrit-data:
  db-data:
  graphite-data:
  rabbitmq-data:
